### ISSUE TITLE
1.8.0 Error: You need to put a chest under the sign.

### ISSUE THREAD

**Issue by husscraft** [SparklingComet/TradeShop#46] opened 2018-01-18 19:16 UTC
Hi, I've just added your plugin to my server as it looks to be the perfect plugin for us. Unfortunately e are getting this error. I saw in the top comment someone else had same issue and your advice was to make sure they were using latest version (1.7.3 at the time) or else to contact you on github. 

As we are having the issue with 1.8.0 , I thought I would try it on 1.7.3 as well. Unfortunately we get the same error still. Any help would be greatly appreciated, as I said, your plugin seems perfect for us.

**Comment by KillerOfPie** [comment] 2018-01-18 19:33
Public server or private? Can I see your config? And any errors show up?

**Comment by husscraft** [comment] 2018-01-18 19:53
Hi, 

It's a public server. No errors on console, in game it says 'you need to put a chest under the sign. I do have griefprevention installed, would that cause an issue?

Here's the config: https://pastebin.com/e7rpfbuc

**Comment by KillerOfPie** [comment] 2018-01-18 19:53
ip?

**Comment by husscraft** [comment] 2018-01-18 19:54
husscraft.mcworlds.pro

**Comment by KillerOfPie** [comment] 2018-01-18 20:29
We found the problem, if you are experiencing this do '/ts reload' we should have a fix out in the next day or two though.

**Comment by KillerOfPie** [comment] 2018-01-20 00:05
Should be fixed in the 1.8.1 release, closing issue.

**Closed as completed by KillerOfPie** 2018-01-20 00:05 UTC
Labels: bug, duplicate

**Comment by SparklingComet** [comment] 2018-01-20 09:37
Duplicate of #43
