### ISSUE TITLE
[BUG] BiTrade messages are confusing

### ISSUE THREAD

**Issue by Svish** [SparklingComet/TradeShop#116] opened 2021-11-20 17:22 UTC
### Expected behavior

Tried to set-up some `[BiTrade]`, and find the error messages very confusing.
```
[BiTrade]
64 PINK_WOOL
4 DIAMOND
```
* ✔ Left-clicking (with pink wool in inventory):  
`"You have traded your 4 diamond for 64 pink_wool with Svish"`
* ❌ Left-clicking (without pink wool in inventory):  
`"You do not have 4 diamond!" (should be "64 pink_wool", no?)`
* ✔ Right-clicking (with diamond in inventory):  
`"You have traded your 4 diamond for 64 pink_wool with Svish"`
* ✔ Right-clicking (without diamond in inventory):  
`"You do not have 4 diamond!"`

Also, when the shop is out of stock with something, it would be good if it said what it was out of stock of. Currently it shows this message, regardless of which trade you're trying to do:  
`"This TradeShop is currently missing items to complete the trade!"`

It's also a bit confusing that the shop itself says `<Out Of Stock>` when there's no more product, even though the cost-item is still in stock so you can do the reverse trade.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/142162/142734142-257d8180-ccda-4def-988c-3f862c720a76.png)

### Steps/models to reproduce

Create a `[BiTrade]` and trade with it, both directions, with and without needed items in chest and/or inventory.

### Plugin list

```
20.11 18:20:22 [Server] INFO Plugins (15): AntiCreeperGrief, Beenfo, CoreProtect, DoorsReloaded, dynmap, FarmProtection, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, OverleveledEnchanter, RHLeafDecay, spark, TradeShop, TreeGravity, WorldEditSelectionVisualizer
```

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

```
20.11 18:20:12 [Server] INFO Checking version, please wait...
20.11 18:20:12 [Server] INFO This server is running Paper version git-Paper-342 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 40ee634)
20.11 18:20:12 [Server] INFO You are 44 version(s) behind
20.11 18:20:12 [Server] INFO Download the new version at: https://papermc.io/downloads
20.11 18:20:12 [Server] INFO Previous version: git-Paper-"3069eae" (MC: 1.17.1)
```
```
20.11 18:20:16 [Server] INFO TradeShop 2.3.1-STABLE by Lori00 & KillerOfPie
```

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

**Comment by KillerOfPie** [comment] 2021-11-20 18:06
Great catches. The code for BiTrades get really confusing since the cost becomes the product and vice versa. Going to number the issues then respond to each.

1. No Stock message does not change while left clicking BiTrade shops
2. Missing items message is not specific enough or not sending in the correct place.
3. BiTrade shops shop oos on sign when they can still trade cost.

**Comment by KillerOfPie** [comment] 2021-11-20 18:09
Now for responses to each.

1. This is definitely a bug caused by the check happening without knowing what trade was requested
2. When exactly does this message appear, I believe this should show up when the shop has not been assigned a cost/product which would be clearly visible on the sign.
3. I thought i had fixed this for 2.4 but I'll look again.

**Comment by Svish** [comment] 2021-11-20 18:57
2. It shows up when both cost and product has been assigned, but one of the items are missing.

**Comment by KillerOfPie** [comment] 2021-11-20 18:58
> 2. It shows up when both cost and product has been assigned, but one of the items are missing.

Okay, but how do you interact with the sign for it to appear, because left/right click should show the messages from 1

**Comment by KillerOfPie** [comment] 2021-11-20 19:05
> > 2. It shows up when both cost and product has been assigned, but one of the items are missing.
> 
> Okay, but how do you interact with the sign for it to appear, because left/right click should show the messages from 1

Never mind I found it.

**Comment by Svish** [comment] 2021-11-20 19:06
If I remove all the wool (but still have diamonds in the chest, and both diamonds and wool in my inventory), then I get the message `"This TradeShop is currently missing items to complete the trade!"` regardless of whether I right- or left-click.

**Comment by KillerOfPie** [comment] 2021-11-20 19:47
All 3 fixed in e030cec

Dev update should be out in a couple minutes

**Closed as completed** 2021-12-31 21:09 UTC
Labels: bug, fix
